<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsXveExtension>true</IsXveExtension>
    <RootNamespace>XamlVisualEditor.TreeInspectorExtension</RootNamespace>
    <Description>Visual/logical tree inspector extension.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="ProDataGrid" />
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\XamlVisualEditor.Extensions\XamlVisualEditor.Extensions.csproj" />
  </ItemGroup>
</Project>
