<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsXveExtension>true</IsXveExtension>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>XamlVisualEditor.SolutionExplorerExtension</RootNamespace>
    <Description>Solution explorer extension</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\XamlVisualEditor.Extensions\XamlVisualEditor.Extensions.csproj" />
  </ItemGroup>
</Project>
