<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsXveExtension>true</IsXveExtension>
    <RootNamespace>XamlVisualEditor.Debugging.DotNetSdkExtension</RootNamespace>
    <Description>.NET SDK debugger integration (vsdbg-based)</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\XamlVisualEditor.Extensions\XamlVisualEditor.Extensions.csproj" />
    <ProjectReference Include="..\XamlVisualEditor.Debugging.DapExtension\XamlVisualEditor.Debugging.DapExtension.csproj" />
  </ItemGroup>
</Project>
