<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsXveExtension>true</IsXveExtension>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>XamlVisualEditor.CollaborationExtension</RootNamespace>
    <Description>Collaboration panel extension</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\XamlVisualEditor.Extensions\XamlVisualEditor.Extensions.csproj" />
  </ItemGroup>
</Project>
